name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main   # change if your default branch is different

permissions:
  contents: write   # needed for pushing to gh-pages branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: 'ruby 3.1.2p20'   # match the Ruby you use locally
=======
          ruby-version: '3.1.2p20'   # match the Ruby you use locally
>>>>>>> 29cf419 (Update jekyll-gh-pages.yml)
          bundler-cache: true   # cache gems to speed up builds

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true
          publish_dir: ./docs/_site
          publish_branch: gh-pages
          force_orphan: true
